api_hash: 2122f2e4c21239eebd0a6725203ecef9
api_id: 28984697
chat:
#Ich.tina
- chat_id: -1001949427513
  last_read_message_id: 0
#Samijo
- chat_id: -1001893706017
  last_read_message_id: 0
#Nonakanal
- chat_id: -1001962975115
  last_read_message_id: 0
#Lisa Kueppers
- chat_id: -1001902523885
  last_read_message_id: 0
#Fayesxh
- chat_id: -1001663662772
  last_read_message_id: 0
#Lucy Lacht
- chat_id: -1001869504964
  last_read_message_id: 0
#Alinaxlove
- chat_id: -1001869504964
  last_read_message_id: 0
#Saftiges Gnu
- chat_id: -1001915547304
  last_read_message_id: 0
#Lara Loft
- chat_id: -1001697209810
  last_read_message_id: 0
#Jasi_xx3
- chat_id: -1001930035023
  last_read_message_id: 0
#Julesboringlife
- chat_id: -1001764672927
  last_read_message_id: 0
#Kayla Shyx
- chat_id: -1001964211512
  last_read_message_id: 0
#Mahluna
- chat_id: -1001954796233
  last_read_message_id: 0
#Fabienne0805
- chat_id: -1001628178164
  last_read_message_id: 0
#Emilia.bte
- chat_id: -1001946825864
  last_read_message_id: 0
#Palina Rojinski
- chat_id: -1001805228832
  last_read_message_id: 0
#Shurjoka
- chat_id: -1001577298504
  last_read_message_id: 0
#Sophodoph
- chat_id: -1001678890342
  last_read_message_id: 0
#Paolaparente
- chat_id: -1001866293956
  last_read_message_id: 0
#Lenimariee
- chat_id: -1001841011249
  last_read_message_id: 0
#Melina Sophie
- chat_id: -1001551342484
  last_read_message_id: 0
#Loredana
- chat_id: -1001820520773
  last_read_message_id: 0
#Itsmisabell
- chat_id: -1001971336678
  last_read_message_id: 0
#Heidiklum
- chat_id: -1001915854087
  last_read_message_id: 0
#Sophia Tomalla
- chat_id: -1001556526571
  last_read_message_id: 0
#Stefanie Giesinger
- chat_id: -1001875772565
  last_read_message_id: 0
#Crizzle
- chat_id: -1001763194761
  last_read_message_id: 0
#Paola Marie
- chat_id: -1001322188942
  last_read_message_id: 0
#Mrs Bella
- chat_id: -1001978192765
  last_read_message_id: 0
#Nathalie Bleicher
- chat_id: -1001825169484
  last_read_message_id: 0
#Lena Gercke
- chat_id: -1001821354167
  last_read_message_id: 0
#Juju44
- chat_id: -1001948733744
  last_read_message_id: 0
#Bettytaube
- chat_id: -1001616549604
  last_read_message_id: 0
#Emaxlouise
- chat_id: -1001931201599
  last_read_message_id: 0
#Jana Riva
- chat_id: -1001954678762
  last_read_message_id: 0
#Enisa.Bukvic
- chat_id: -1001963668172
  last_read_message_id: 0
#Davina Geiss
- chat_id: -1001880804045
  last_read_message_id: 0
#Ebru
- chat_id: -1001588297683
  last_read_message_id: 0
#Blanca Friedrich
- chat_id: -1001498692348
  last_read_message_id: 0
#Vallixpauline
- chat_id: -1001980220166
  last_read_message_id: 0
#Alicia Schmidt
- chat_id: -1001880269627
  last_read_message_id: 0
#Kelly Missesvlog
- chat_id: -1001976491146
  last_read_message_id: 0
#Leakatharinamaria
- chat_id: -1001552154196
  last_read_message_id: 0
#Starlet Nova
- chat_id: -1001629257417
  last_read_message_id: 0
#Payton.r
- chat_id: -1001956749346
  last_read_message_id: 0
#Pamela Reif
- chat_id: -1001942315578
  last_read_message_id: 0
#Nadine Breaty
- chat_id: -1001883077798
  last_read_message_id: 0
#KDR Kitten
- chat_id: -1001989009454
  last_read_message_id: 0
#Lea Looskanal
- chat_id: -1001869592043
  last_read_message_id: 0
#Nikasofie
- chat_id: -1001213288579
  last_read_message_id: 0
#Alinamour
- chat_id: -1001983553352
  last_read_message_id: 0
#Leni Klum
- chat_id: -1001691975389
  last_read_message_id: 0
#Leoobalys
- chat_id: -1001815878207
  last_read_message_id: 0
#RevedTV
- chat_id: -1001838227892
  last_read_message_id: 0
#Regina Hixt
- chat_id: -1001867826278
  last_read_message_id: 0
#Kunshikitty
- chat_id: -1001816345488
  last_read_message_id: 0
#BibisBeauty
- chat_id: -1001810574791
  last_read_message_id: 0
#Alinamour
- chat_id: -1001983553352
  last_read_message_id: 0
#Honeypuu
- chat_id: -1001893644471
  last_read_message_id: 0
#DeniseMski
- chat_id: -1001687769444
  last_read_message_id: 0

# note we remove ids_to_retry to data.yaml
ids_to_retry: []
media_types:
- audio
- document
- photo
- video
- voice
- animation #gif
file_formats:
  audio:
  - all
  document:
  - pdf
  - epub
  video:
  - mp4
save_path: Q:/Telegram
file_path_prefix:
- chat_title
hide_file_name: false
file_name_prefix:
- message_id
- file_name
file_name_prefix_split: ' - '
max_download_task: 5
web_host: 127.0.0.1
web_port: 5000
language: EN
web_login_secret: 123
allowed_user_ids:
- me
date_format: '%Y_%m'
